# Generated by Django 5.1.1 on 2024-10-29 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Anime nomi')),
                ('description', models.TextField(verbose_name="Ma'lumot")),
                ('release_date', models.DateField(verbose_name='Chiqarilga sana')),
                ('episode_count', models.PositiveIntegerField(verbose_name='Qismlar soni')),
                ('cover_image', models.ImageField(upload_to='anime/covers/', verbose_name='Rasm')),
                ('download_file', models.FileField(blank=True, null=True, upload_to='anime/files/', verbose_name='Animelar file yuklanish joyi')),
                ('views', models.IntegerField(default=0)),
                ('coments_count', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(to='app.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animelar',
            },
        ),
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Isim')),
                ('text', models.TextField(max_length=1000, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.anime', verbose_name='Anime')),
            ],
            options={
                'verbose_name': 'Komentariya',
                'verbose_name_plural': 'Komentariyalar',
            },
        ),
    ]
