# Generated by Django 5.1.1 on 2024-10-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_anime_download_file_alter_anime_episode_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='anime',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='anime/headers/', verbose_name='Header rasm'),
        ),
        migrations.AddField(
            model_name='anime',
            name='header_publish',
            field=models.BooleanField(default=False, verbose_name='Headerni chiqarish'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Studio nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Kategoriya slug'),
        ),
    ]
