# Generated by Django 5.1.1 on 2024-10-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_options_anime_header_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='studio',
        ),
        migrations.AlterField(
            model_name='anime',
            name='coments_count',
            field=models.IntegerField(default=0, verbose_name='Izohlar Soni'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='cover_image',
            field=models.ImageField(upload_to='covers/', verbose_name='Qopqoq Rasm'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episode_count',
            field=models.IntegerField(verbose_name='Epizodlar Soni'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='header_image',
            field=models.ImageField(default='https://coffective.com/wp-content/uploads/2018/06/default-featured-image.png.jpg', upload_to='headers/', verbose_name='Header Rasm'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='header_publish',
            field=models.BooleanField(default=False, verbose_name='Headerni Chop Etish'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release_date',
            field=models.DateField(verbose_name='Chiqarilish Sanasi'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Anime Sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='views',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar Soni"),
        ),
    ]
